// 初始 Seed Data - 85个常用网站

import { Group, Bookmark } from '@/types';
import { generateId } from '@/utils';

export const DEFAULT_GROUPS: Group[] = [
  {
    id: 'group-ai',
    name: 'AI 工具',
    icon: 'sparkles',
    color: '#8b5cf6',
    hidden: false,
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-dev',
    name: '开发',
    icon: 'code',
    color: '#06b6d4',
    hidden: false,
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-design',
    name: '设计',
    icon: 'palette',
    color: '#ec4899',
    hidden: false,
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-work',
    name: '工作',
    icon: 'briefcase',
    color: '#f59e0b',
    hidden: false,
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-tools',
    name: '工具箱',
    icon: 'wrench',
    color: '#10b981',
    hidden: false,
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-media',
    name: '影音',
    icon: 'music',
    color: '#ef4444',
    hidden: false,
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'group-entertainment',
    name: '娱乐',
    icon: 'gamepad-2',
    color: '#22c55e',
    hidden: false,
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_BOOKMARKS: Bookmark[] = [
  // ========== AI 工具 ==========
  {
    id: generateId(),
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Claude',
    url: 'https://claude.ai',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Gemini',
    url: 'https://gemini.google.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '通义千问',
    url: 'https://tongyi.aliyun.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '文心一言',
    url: 'https://yiyan.baidu.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Kimi',
    url: 'https://kimi.moonshot.cn',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Cursor',
    url: 'https://cursor.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Midjourney',
    url: 'https://www.midjourney.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Stable Diffusion',
    url: 'https://stability.ai',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-ai',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 开发工具 ==========
  {
    id: generateId(),
    title: 'GitHub',
    url: 'https://github.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'GitLab',
    url: 'https://gitlab.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'MDN',
    url: 'https://developer.mozilla.org',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'npm',
    url: 'https://www.npmjs.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Docker Hub',
    url: 'https://hub.docker.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Vercel',
    url: 'https://vercel.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Cloudflare',
    url: 'https://dash.cloudflare.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Gitee',
    url: 'https://gitee.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '掘金',
    url: 'https://juejin.cn',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // 新增开发者宝藏网站
  {
    id: generateId(),
    title: 'Roadmap.sh',
    url: 'https://roadmap.sh',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Learn X in Y Minutes',
    url: 'https://learnxinyminutes.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'DevDocs',
    url: 'https://devdocs.io',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'JSON Crack',
    url: 'https://jsoncrack.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Crontab Guru',
    url: 'https://crontab.guru',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-dev',
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 设计工具 ==========
  {
    id: generateId(),
    title: 'Figma',
    url: 'https://figma.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Miro',
    url: 'https://miro.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Excalidraw',
    url: 'https://excalidraw.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Unsplash',
    url: 'https://unsplash.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Font Awesome',
    url: 'https://fontawesome.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Google Fonts',
    url: 'https://fonts.google.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Coolors',
    url: 'https://coolors.co',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '稿定设计',
    url: 'https://www.gaoding.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // 新增设计宝藏网站
  {
    id: generateId(),
    title: 'tldraw',
    url: 'https://tldraw.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-design',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 工作工具 ==========
  {
    id: generateId(),
    title: 'Notion',
    url: 'https://notion.so',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Linear',
    url: 'https://linear.app',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Slack',
    url: 'https://slack.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Trello',
    url: 'https://trello.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '飞书',
    url: 'https://feishu.cn',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '钉钉',
    url: 'https://dingtalk.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '企业微信',
    url: 'https://work.weixin.qq.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '语雀',
    url: 'https://www.yuque.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'WPS',
    url: 'https://www.wps.cn',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // 新增工作宝藏网站
  {
    id: generateId(),
    title: 'Zapier',
    url: 'https://zapier.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'n8n',
    url: 'https://n8n.io',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Otter.ai',
    url: 'https://otter.ai',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Loom',
    url: 'https://loom.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'AlternativeTo',
    url: 'https://alternativeto.net',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'BuiltWith',
    url: 'https://builtwith.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-work',
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 工具箱 ==========
  {
    id: generateId(),
    title: 'Web Archive',
    url: 'https://web.archive.org',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Temp Mail',
    url: 'https://temp-mail.org',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'FutureMe',
    url: 'https://futureme.org',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Cleanup.pictures',
    url: 'https://cleanup.pictures',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Photopea',
    url: 'https://photopea.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Remove.bg',
    url: 'https://remove.bg',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'LetsEnhance',
    url: 'https://letsenhance.io',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'TinyWow',
    url: 'https://tinywow.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'PDF24',
    url: 'https://pdf24.org',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Dictation.io',
    url: 'https://dictation.io',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Descript',
    url: 'https://descript.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'CamelCamelCamel',
    url: 'https://camelcamelcamel.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'JustTheRecipe',
    url: 'https://justtherecipe.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'CopyChar',
    url: 'https://copychar.cc',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Screenshot Guru',
    url: 'https://screenshot.guru',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'WordCounter',
    url: 'https://wordcounter.net',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Untools',
    url: 'https://untools.co',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-tools',
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 影音 ==========
  {
    id: generateId(),
    title: 'Pixabay',
    url: 'https://pixabay.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-media',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Mixkit',
    url: 'https://mixkit.co',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-media',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ========== 娱乐 ==========
  {
    id: generateId(),
    title: 'Radio Garden',
    url: 'https://radio.garden',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'YouTube',
    url: 'https://youtube.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Twitter/X',
    url: 'https://twitter.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Reddit',
    url: 'https://reddit.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Bilibili',
    url: 'https://bilibili.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '微博',
    url: 'https://weibo.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '知乎',
    url: 'https://zhihu.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '抖音',
    url: 'https://www.douyin.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: '小红书',
    url: 'https://www.xiaohongshu.com',
    region: 'CN',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Spotify',
    url: 'https://spotify.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    title: 'Netflix',
    url: 'https://netflix.com',
    region: 'Global',
    regionManual: false,
    hidden: false,
    groupId: 'group-entertainment',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_SETTINGS = {
  secretCode: '000',
  triggerZone: 'bottom-left' as const,
  lockDuration: 60000,
  showRegionLabels: true,
  compactMode: false,
  storageQuota: 100,
};
